# Generated by Django 4.2.3 on 2023-09-23 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="agent_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_name", models.CharField(max_length=100)),
                ("dob", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("contact_no", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="customer_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_firstname", models.CharField(max_length=100)),
                ("customer_lastname", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("mobile_no", models.CharField(max_length=100)),
                ("email_id", models.CharField(max_length=100)),
                (
                    "image",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="customer_policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.CharField(max_length=100)),
                ("installment_amount", models.CharField(max_length=100)),
                ("policy_start_date", models.CharField(max_length=100)),
                ("policy_end_date", models.CharField(max_length=100)),
                (
                    "agent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insuranceclaim.agent_details",
                    ),
                ),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insuranceclaim.customer_details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="feedback_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("feedback_msg", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="insurance_company_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insurance_name", models.CharField(max_length=100)),
                ("insurance_address", models.CharField(max_length=100)),
                ("insurance_city", models.CharField(max_length=100)),
                ("insurance_contact_no", models.CharField(max_length=100)),
                ("website", models.CharField(max_length=100)),
                ("email_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="loginform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("usertype", models.CharField(max_length=100)),
                ("hintq", models.CharField(max_length=100)),
                ("hinta", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="vehicle_claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_type", models.CharField(max_length=100)),
                ("vehicle_number", models.CharField(max_length=100)),
                ("vehicle_name", models.CharField(max_length=100)),
                ("vehicle_value", models.CharField(max_length=100)),
                ("vehicle_condition", models.CharField(max_length=100)),
                (
                    "image_1",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="vehical/"
                    ),
                ),
                (
                    "image_2",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="vehical/"
                    ),
                ),
                (
                    "image_3",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="vehical/"
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insuranceclaim.customer_details",
                    ),
                ),
                (
                    "customer_policy_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insuranceclaim.customer_policy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="policy_plan_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_number", models.CharField(max_length=100)),
                ("policy_name", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
                ("policy_details", models.CharField(max_length=100)),
                (
                    "company_id",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insuranceclaim.insurance_company_details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="policy_payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid_amount", models.CharField(max_length=100)),
                ("paid_data", models.CharField(max_length=100)),
                (
                    "customer_policy_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insuranceclaim.customer_policy",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer_policy",
            name="policy_plan_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="insuranceclaim.policy_plan_details",
            ),
        ),
        migrations.CreateModel(
            name="claim_amount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_valuation", models.CharField(max_length=100)),
                ("release_date", models.CharField(max_length=100)),
                ("release_amount", models.CharField(max_length=100)),
                (
                    "customer_policy_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insuranceclaim.customer_policy",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agent_details",
            name="company_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="insuranceclaim.insurance_company_details",
            ),
        ),
    ]
